{% set name = "compass" %}
{% set version = "1.0.0" %}
{% set build = 0 %}

{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: {{ build }}
  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `PKG_NAME * mpi_mpich_*` for mpich
  # `PKG_NAME * mpi_*` for any mpi
  # `PKG_NAME * nompi_*` for no mpi
  string: "{{ mpi_prefix }}_py_h{{ PKG_HASH }}_{{ build }}"
  entry_points:
    - compass = compass.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - geometric_features 0.1.13
    - mpas_tools 0.2.0
    - jigsaw 0.9.12
    - jigsawpy 0.2.1
    - metis
    - cartopy_offlinedata
    - ffmpeg
    - {{ mpi }}  # [mpi != 'nompi']
    - esmf * {{ mpi_prefix }}_*
    - netcdf4 * nompi_*
    - nco
    - pyremap >=0.0.7,<0.1.0
    - rasterio
    - affine
    - ipython
    - jupyter
    - lxml
    - matplotlib-base
    - cmocean
    - numpy
    - xarray
    - progressbar2
    - requests
    - scipy
    - git

test:
  imports:
    - compass
  commands:
    - compass list
    - compass list --help
    - compass setup --help
    - compass suite --help
    - compass clean --help
    - gpmetis --help
    - ffmpeg -help

about:
  home: https://github.com/MPAS-Dev/compass
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Test cases for the Model for Prediction Across Scales (MPAS)'
  description: |
    Configuration Of Model for Prediction Across Scales Setups (COMPASS) is an
    automated system to set up test cases that match the MPAS-Model repository.
    All namelists and streams files begin with the default generated from the
    Registry.xml file, and only the changes relevant to the particular test
    case are altered in those files.
  doc_url: https://mpas-dev.github.io/compass/stable/
  dev_url: https://github.com/MPAS-Dev/compass

extra:
  recipe-maintainers:
    - xylar
