{% set name = "compass" %}
{% set version = "1.2.0alpha.4" %}
{% set build = 0 %}

{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../..

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: {{ build }}
  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `PKG_NAME * mpi_mpich_*` for mpich
  # `PKG_NAME * mpi_*` for any mpi
  # `PKG_NAME * nompi_*` for no mpi
  string: "{{ mpi_prefix }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}"
  entry_points:
    - compass = compass.__main__:main
    - create_compass_load_script = compass.load:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - cartopy
    - cartopy_offlinedata
    - cmocean
    - esmf * {{ mpi_prefix }}_*
    - ffmpeg
    - geometric_features 1.0.1
    - git
    - ipython
    - jigsaw 0.9.14
    - jigsawpy 0.3.3
    - jupyter
    - lxml
    - mache 1.10.0
    - matplotlib-base
    - metis
    - mpas_tools 0.17.0
    - nco
    - netcdf4 * nompi_*
    - numpy
    - otps 2021.10  # [linux]
    - progressbar2
    - pyamg >=4.2.2
    - pyproj
    - pyremap >=0.0.13,<0.1.0
    - requests
    - scipy >=1.8.0
    - shapely >=2.0,<3.0
    - xarray

# tools for building MPAS components
{% if mpi != "nompi" %}
    - c-compiler
    - cmake
    - cxx-compiler
    - fortran-compiler
    - hdf5 * {{ mpi_prefix }}_*
    - libnetcdf * {{ mpi_prefix }}_*
    - libpnetcdf 1.12.2 {{ mpi_prefix }}_*
    - m4
    - make
    - {{ mpi }}
    - netcdf-fortran
    - scorpio 1.3.2 {{ mpi_prefix }}_*
{% endif %}

test:
  requires:
    - pip
  imports:
    - compass
  commands:
    - compass list
    - compass list --machines
    - compass list --suites
    - compass list --help
    - compass setup --help
    - compass suite --help
    - compass clean --help
    - create_compass_load_script --help
    - pip check


about:
  home: https://github.com/MPAS-Dev/compass
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Test cases for the Model for Prediction Across Scales (MPAS)'
  description: |
    Configuration Of Model for Prediction Across Scales Setups (COMPASS) is an
    automated system to set up test cases that match the MPAS-Model repository.
    All namelists and streams files begin with the default generated from the
    Registry.xml file, and only the changes relevant to the particular test
    case are altered in those files.
  doc_url: https://mpas-dev.github.io/compass/latest/
  dev_url: https://github.com/MPAS-Dev/compass

extra:
  recipe-maintainers:
    - xylar
