#!/bin/bash
#SBATCH  --job-name={{ EXP }}
#SBATCH  --account=m1795
#SBATCH  --nodes=5
#SBATCH  --tasks-per-node=64
#SBATCH  --exclusive
#SBATCH  --time=12:00:00
#SBATCH  --qos=premium
#SBATCH  --constraint=haswell

LOGDIR=previous_logs_`date +"%Y-%m-%d_%H-%M-%S"`
mkdir $LOGDIR
cp log* $LOGDIR

# CHANGE THIS TO YOUR COMPASS LOAD SCRIPT!
source /global/cscratch1/sd/hoffman2/AIS8km/compass/load_dev_compass_1.2.0-alpha.1_cori-haswell_gnu_mpt_albany.sh
date
srun -n 320 --cpu-bind=cores --hint=nomultithread ./landice_model
date
