{% set version = "2021.10" %}
{% set build = 0 %}

package:
  name: otps
  version: {{ version }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - make
    - {{ compiler('fortran') }}
  host:
    - gdown
    - tar

test:
  commands:
    - test -f ${PREFIX}/bin/extract_HC
    - test -f ${PREFIX}/bin/extract_local_model
    - test -f ${PREFIX}/bin/predict_tide

about:
  home: https://www.tpxo.net/otps
  license: custom
  license_file: OTPS/COPYRIGHT
  summary: OSU TIDAL PREDICTION Software (OTPS)

extra:
  recipe-maintainers:
    - xylar
    - sbrus89
