<streams>

<immutable_stream name="input_init"
        filename_template="mesh.nc">
</immutable_stream>

<stream name="output_init"
        type="output"
        output_interval="0000_00:00:01"
        clobber_mode="truncate"
        filename_template="initial_state.nc">

    <stream name="input_init"/>
    <var_struct name="tracers"/>
    <var name="refZMid"/>
    <var name="normalVelocity"/>
    <var name="layerThickness"/>
    <var name="restingThickness"/>
    <var name="surfaceStress"/>
    <var name="atmosphericPressure"/>
    <var name="boundaryLayerDepth"/>
    <var name="refBottomDepth"/>
    <var name="bottomDepth"/>
    <var name="bottomDepthObserved"/>
    <var name="maxLevelCell"/>
    <var name="vertCoordMovementWeights"/>
    <var name="edgeMask"/>
    <var name="cullCell"/>
</stream>

</streams>
