<streams>

<immutable_stream name="input_init"
        filename_template="mesh.nc">
</immutable_stream>

<stream name="bathymetry"
        filename_template="mesh.nc"
        type="input"
        input_interval="initial_only">

    <var name="bottomDepthObserved"/>
</stream>

<stream name="output_init"
        type="output"
        output_interval="0000_00:00:01"
        clobber_mode="truncate"
        filename_template="ocean.nc">

    <stream name="input_init"/>
    <var_struct name="tracers"/>
    <var name="refZMid"/>
    <var name="normalVelocity"/>
    <var name="layerThickness"/>
    <var name="restingThickness"/>
    <var name="refBottomDepth"/>
    <var name="bottomDepth"/>
    <var name="bottomDepthObserved"/>
    <var name="maxLevelCell"/>
    <var name="vertCoordMovementWeights"/>
    <var name="ssh"/>
    <var name="bottomDrag"/>
</stream>

</streams>
