<streams>

<immutable_stream name="input_init"
                  filename_template="culled_mesh.nc"/>

<stream name="output_init"
        type="output"
        output_interval="0000_00:00:01"
        clobber_mode="truncate"
        filename_template="ocean.nc">

    <stream name="input_init"/>
    <var_struct name="tracers"/>
    <var name="bottomDepth"/>
    <var name="refZMid"/>
    <var name="refBottomDepth"/>
    <var name="maxLevelCell"/>
    <var name="normalVelocity"/>
    <var name="layerThickness"/>
    <var name="restingThickness"/>
    <var name="cullCell"/>
    <var name="ssh"/>
</stream>

</streams>
