name: CI/CD Release Workflow

on:
  push:
    branches: [main, legacy]

  release:
    types: [published]

env:
  PYTHON_VERSION: "3.13"

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      docs_version: "latest"
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: "compass_ci"
          miniforge-version: latest
          channels: conda-forge,e3sm/label/compass
          channel-priority: strict
          use-mamba: false
          auto-update-conda: true
          python-version: ${{ env.PYTHON_VERSION }}

      - if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        name: Install compass
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          ./conda/configure_compass_env.py \
            --env_only \
            --env_name compass_test \
            --python=${{ env.PYTHON_VERSION }} \
            --verbose
          source load_compass_test.sh

      - name: Build Sphinx Docs
        run: |
          source load_compass_test.sh
          cd docs
          if [[ $GITHUB_REF_NAME == "main" ]]; then
              export DOCS_VERSION="latest"
          else
              export DOCS_VERSION=${GITHUB_REF_NAME}
          fi
          echo "Docs version: $DOCS_VERSION"
          echo "docs_version=$DOCS_VERSION" >> $GITHUB_ENV
          make html
      - name: Copy Docs and Commit
        run: |
          source load_compass_test.sh
          cd docs
          # gh-pages branch must already exist
          git clone https://github.com/MPAS-Dev/compass.git --branch gh-pages --single-branch gh-pages
          # Make sure we're in the gh-pages directory.
          cd gh-pages
          # Create `.nojekyll` (if it doesn't already exist) for proper GH Pages configuration.
          touch .nojekyll
          # Add `index.html` to point to the `main` branch automatically.
          printf '<meta http-equiv="refresh" content="0; url=./main/index.html" />' > index.html
          # Only replace `main` docs with latest changes. Docs for releases should be untouched.
          export DOCS_VERSION="${{ env.docs_version }}"
          rm -rf ${DOCS_VERSION}
          mkdir ${DOCS_VERSION}
          cp -r ../_build/html/* ${DOCS_VERSION}
          # Configure git using GitHub Actions credentials.
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # The second command will fail if no changes were present, so we ignore it
          git add .
          git commit -m "Update documentation" -a || true
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: docs/gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
